python3 pt-hsemotion-inference.py
python3 pt-dan-inference.py
python3 pt-gus-inference.py
python3 pt-hsemotion-dan-inference.py
python3 pt-hsemotion-gus-inference.py
python3 pt-hsemotion-dangus-inference.py
python3 pt-hsemotion-dangus-v2-inference.py
python3 pt-mobilenet-inference.py
python3 pt-mobilevit-inference.py
python3 pt-edgenext-inference.py